import pytest

from lisa.files import file_kind, generated_rules, header_lines, should_skip
from lisa.models import Line


@pytest.mark.parametrize(
    "path, kind",
    [
        ("src/app.ts", "code"),
        ("scripts/build.py", "code"),
        ("docs/guide.md", "prose"),
        ("AGENTS.md", "prose"),
        ("notes.txt", "prose"),
        ("packages/sdk/openapi.json", "config"),
        (".github/workflows/ci.yml", "config"),
        ("pyproject.toml", "config"),
        ("packages/sdk/js/src/gen/types.gen.ts", "generated"),
        ("api/service_pb2.py", "generated"),
        ("api/service.pb.go", "generated"),
        ("ui/__generated__/schema.ts", "generated"),
        ("Models.generated.cs", "generated"),
    ],
)
def test_file_kinds_by_name(path, kind):
    assert file_kind(path, []) == kind


@pytest.mark.parametrize(
    "header",
    [
        ["// Code generated by protoc-gen-go. DO NOT EDIT."],
        ["/* eslint-disable */", "// @generated"],
        ["# This file was automatically generated by tool X"],
        ["// auto-generated, edits will be lost"],
    ],
)
def test_generator_markers_in_the_header_mark_generated_code(header):
    assert file_kind("src/client.ts", header) == "generated"


def test_ordinary_comments_about_generation_are_not_markers():
    assert file_kind("src/tokens.ts", ["// Tokens generated for each session expire after an hour."]) == "code"


def test_gitattributes_rules_decide_and_later_rules_win():
    rules = generated_rules(
        "# comment\n"
        "*.snapshot.ts linguist-generated\n"
        "packages/sdk/** linguist-generated=true\n"
        "packages/sdk/handwritten.ts -linguist-generated\n"
        "*.md text eol=lf\n"
    )
    assert file_kind("src/a.snapshot.ts", [], rules) == "generated"
    assert file_kind("packages/sdk/client.ts", [], rules) == "generated"
    assert file_kind("packages/sdk/handwritten.ts", [], rules) == "code"
    # An explicit "not generated" rule overrides a name that looks generated.
    assert file_kind("packages/sdk/handwritten.ts", ["// @generated"], rules) == "code"


def test_prose_stays_prose_even_when_generated():
    assert file_kind("Third-Party-Notices.md", ["<!-- @generated -->"]) == "prose"


def test_header_lines_are_the_first_lines_of_the_new_file():
    lines = [Line("+", "// @generated", 1), Line("-", "old", None), Line(" ", "x", 2), Line("+", "late", 9)]
    assert header_lines(lines) == ["// @generated", "x"]


def test_skipped_files():
    for path in ["package-lock.json", "web/yarn.lock", "uv.lock", "static/app.min.js", "vendor/x.go", "logo.PNG"]:
        assert should_skip(path), path
    assert not should_skip("src/lock.py")
