"""Decides how each changed file is treated: skipped entirely, or reviewed as code, config, prose,
or generated code.

File names and file headers come from the pull request author, so a file's kind only turns off
*quality* checks (complexity, duplication). The security checks keep running on every kind a
security problem can live in; see `files` on the built-in checks."""

import posixpath
import re
from fnmatch import fnmatchcase

from lisa.models import Line

SKIPPED = [
    re.compile(
        r"(^|/)(package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|Cargo\.lock"
        r"|poetry\.lock|uv\.lock|Pipfile\.lock|go\.sum|composer\.lock|Gemfile\.lock)$"
    ),
    re.compile(r"\.min\.(js|css)$"),
    re.compile(r"\.(map|snap|svg)$"),
    re.compile(r"(^|/)(node_modules|vendor)/"),
    re.compile(
        r"\.(png|jpe?g|gif|webp|ico|bmp|tiff?|pdf|zip|gz|tgz|bz2|xz|7z|rar|jar|war|class|woff2?|ttf|otf|eot"
        r"|mp[34]|mov|avi|webm|wav|ogg|flac|wasm|so|dylib|dll|exe|bin|o|a|pyc|db|sqlite)$",
        re.IGNORECASE,
    ),
]
PROSE = re.compile(r"\.(md|mdx|markdown|rst|txt|adoc)$", re.IGNORECASE)
CONFIG = re.compile(r"\.(json|jsonc|json5|ya?ml|toml|ini|cfg|conf|properties|xml|plist|csv|tsv)$", re.IGNORECASE)
# Common names for generated code: foo.gen.ts, foo.generated.cs, foo_pb2.py, foo.pb.go, __generated__/.
GENERATED_NAME = re.compile(
    r"(\.gen|\.generated|_generated|_pb2|_pb2_grpc|\.pb)\.[A-Za-z0-9]+$|(^|/)__generated__/", re.IGNORECASE
)
# Markers generators write at the top of a file.
GENERATED_MARKER = re.compile(
    r"@generated|do not edit|auto-?generated|code generated by|this file (is|was) (automatically )?generated",
    re.IGNORECASE,
)
HEADER_LINES = 5


def should_skip(path: str) -> bool:
    """Lockfiles, binaries, minified bundles, and vendored code: listed in the summary, not reviewed."""
    return any(pattern.search(path) for pattern in SKIPPED)


def generated_rules(gitattributes: str) -> tuple[tuple[str, bool], ...]:
    """The `linguist-generated` rules in a .gitattributes file, in order, as (pattern, generated)."""
    rules = []
    for line in gitattributes.splitlines():
        parts = line.split()
        if not parts or parts[0].startswith("#"):
            continue
        for attribute in parts[1:]:
            if attribute in ("linguist-generated", "linguist-generated=true"):
                rules.append((parts[0], True))
            elif attribute in ("-linguist-generated", "!linguist-generated", "linguist-generated=false"):
                rules.append((parts[0], False))
    return tuple(rules)


def _matches(path: str, pattern: str) -> bool:
    """Approximates gitattributes matching: a pattern without a slash matches the file name in
    any directory; otherwise it matches from the repository root."""
    if "/" not in pattern.strip("/"):
        return fnmatchcase(posixpath.basename(path), pattern.strip("/"))
    return fnmatchcase(path, pattern.lstrip("/").replace("**/", "*"))


def file_kind(path: str, header: list[str], rules: tuple[tuple[str, bool], ...] = ()) -> str:
    """One of FILE_KINDS. `header` is the first lines of the new file, when the diff shows them;
    `rules` come from the base branch's .gitattributes."""
    if PROSE.search(path):
        return "prose"
    # The last matching .gitattributes rule decides; without one, names and header markers do.
    marked = [generated for pattern, generated in rules if _matches(path, pattern)]
    if marked:
        generated = marked[-1]
    else:
        generated = bool(GENERATED_NAME.search(path)) or any(GENERATED_MARKER.search(line) for line in header)
    if generated:
        return "generated"
    return "config" if CONFIG.search(path) else "code"


def header_lines(lines: list[Line]) -> list[str]:
    """The first lines of the new file among a diff's lines, if the diff reaches the top of the file."""
    return [line.text for line in lines if line.number is not None and line.number <= HEADER_LINES]
